name: project_cs_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: "^0.18.4+1"
  cupertino_icons: ^1.0.0
  tflite_flutter: ^0.5.0
  tflite_flutter_helper: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
